apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sckdhogv
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-sckdhogv:d71bdd40720df2485407914b83a991747948c4af@sha256:b6ee926ccc40cdf0d2170029c6e228f91f321787b6783f67c60f8506eaf6c88a
          name: container-image
